require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.2
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/bundle'
    - 'db/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 99
  IgnoredPatterns: ['\A#']

Style/Documentation:
  Enabled: false
