require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.2
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/bundle'
    - 'db/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Metrics/LineLength:
  Max: 99
  IgnoredPatterns: ['\A#']
  Exclude:
    - 'config/initializers/*.rb'

Style/Documentation:
  Enabled: false
